version: '2.4'

services:
  mongo-express:
    image: mongo-express:latest
    ports:
      - "50100:8081"
    restart: always
    environment:
      ME_CONFIG_SITE_BASEURL: "/mongodb"
      ME_CONFIG_BASICAUTH_USERNAME: "mongoweb"
      ME_CONFIG_BASICAUTH_PASSWORD: "password"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_SERVER: "192.168.0.171"
      ME_CONFIG_MONGODB_PORT: "50101"
