---
# tasks file for tools

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Set selinux to permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Install required packages
  yum:
    name: "{{ item.pkg }}"
    state: latest
  with_items:
  - { pkg: yum-utils }

- name: Configure docker-ce repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    warn: no

- name: Install docker-ce
  yum:
    name: docker-ce
    state: latest

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Download kubectl binary
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'