---
# tasks file for nginx

- name: Enable epel-release repository
  yum:
    name: epel-release
    state: latest

- name: Install nginx package
  yum:
    name: nginx
    state: latest

- name: Copy nginx config files
  copy:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  with_items:
    - { source: files/nginx.conf, destination: /etc/nginx/nginx.conf }
    - { source: files/nginx-nosql-poc.conf, destination: /etc/nginx/conf.d/nginx-nosql-poc.conf }

- name: Start and enable nginx server
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Copy kubeconfig file to manage PoC environment
  copy: 
    src: /tmp/{{ item }}/kube_config_rancher-cluster.yaml 
    dest: /root/nginx-nosql-poc.yaml
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ groups.k8s }}"

- name: Install git package
  yum:
    name: git
    state: latest

- name: Clone git repo with setup files
  git:
    repo: https://github.com/kkurpanik/nginx-nosql-poc.git
    dest: /root/nginx-nosql-poc

- name: Install docker compose
  command: pip3 install docker-compose
  args:
    warn: no