---
# tasks file for nginx

- name: Enable epel-release repository
  yum:
    name: epel-release
    state: latest

- name: Install nginx package
  yum:
    name: nginx
    state: latest

- name: Enable nginx server
  service:
    name: nginx
    enabled: yes