kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongodb
    type: DirectoryOrCreate
