apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-claim0
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: couchdb-pv0
