apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3168
      targetPort: 3168
      protocol: TCP
      name: mysql
  selector:
    name: mariadb
